# Generated by Django 5.1 on 2024-09-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userIncome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceModel',
            new_name='Source',
        ),
    ]
